.TH HASHING 1 2024-04-14 Linux

.SH NAME
hashing \- compute hash algorithm checksum

.SH SYNOPSIS
.B hashing
[\fIOPTION\fR]... [\fIFILE\fR]...

.SH DESCRIPTION
.B hashing
computes the checksum of a file or some input from stdin using the supplied hash algorithm.

.SH OPTIONS
.TP
.BR \-a ", " \fB\-\-algorithm " " \fI <algorithm>
The hash algorithm to use when computing the checksum.

See \fBALGORITHMS\fR for which hash algorithms is supported.

Note: When no algorithm is supplied, \fBsha256\fR is used.

.TP
.BR \-d ", " \fB\-\-depth " " \fI <depth>
When supplying one or more directories, the depth is the limit of how deep to search for files.

Note: When no depth is supplied, the program will search indefinitely. To specify the program to search indefinitely, supply the depth \fB-1\fR.

.TP
.BR \-c ", " \fB\-\-concat
When supplying more than one file, \fBconcatonate\fR the data and create a single hash checksum.

.SH ALGORITHMS
.TP
.BR sha256 " (defualt)"
SHA256 produces a 256 bit hash, which here is represented by a 64 character hex string.

.TP
.BR md5
MD5 produces a 128 bit hash, which here is represented by a 32 character hex string.

.SH AUTHOR
Written by Hampus Fridholm.

.SH SEE ALSO
\fBsha256sum\fR(1),
\fBmd5sum\fR(1)
